M48
; DRILL file {KiCad 7.99.0-728-gadc213a04d-dirty} date Fri 05 May 2023 05:39:17 AM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-05T05:39:17+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-728-gadc213a04d-dirty
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0118
%
G90
G05
T1
X4.909Y-5.2362
X4.909Y-5.4638
T0
M30
