M48
; DRILL file {KiCad 7.99.0-950-gc4668c1d3a-dirty} date Thu 01 Jun 2023 03:31:43 AM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-01T03:31:43+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-950-gc4668c1d3a-dirty
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0118
%
G90
G05
T1
X1.7295Y-2.2438
X1.7295Y-2.4714
T0
M30
