M48
; DRILL file {KiCad 7.99.0-728-gadc213a04d-dirty} date Sat 29 Apr 2023 04:02:42 AM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-29T04:02:42+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-728-gadc213a04d-dirty
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0118
%
G90
G05
T1
X4.9086Y-5.1362
X4.9086Y-5.3638
T0
M30
